[[finufft]]
arch = "aarch64"
git-tree-sha1 = "b3e91ffb04181ec1ca82ae27408e51dead40ab4f"
lazy = true
os = "macos"

    [[finufft.download]]
    sha256 = "e9bd1a294354ed3b51211f08ddae43cdff420748439de02bd40deda5c5afa67d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "86ccc3c7f2dd7502dfb361f63771294fc83d19c8"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "fe295ac9b3de6d1270f177ee233cfd80e1368c8760fc9d018e3b84ac4a95d2e3"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "f5f338c74a8c542a281d21780d2d292ebed8a54a"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "b363f1a347d38cf4172610e84852787ad6f1a6228d32a6e6a18fcb7646c2fae7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "c72d9b596e49bf7b60748bee83d71b09d099296b"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "f0ce7b43edba3d558939879cf0193cf78ff0b8dccc806f8b95e546fcd39de386"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "bb0afc18e5eddd77f39c70dbc986f097d572734e"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "9e97b0f07e7290836bae44eec4da1ed3c7433d256c3e138f68ab5cbff9c17220"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16e760641a96ec3c9532dc546c75204f08dee079"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "f46d2fd60c05b28c5582bf64f993ea838ebb630c9e7b7359ad63a01e139bbd54"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44c3e1da29fcbe0241a43c6a57c5fe3eb121b4b5"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "93c548663a286e58ff6deaebab80e3ccd738794250822b76aaa13e2a48dbfabe"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "e846f0fb07b88dbd7c12efc7955e434dc751a07a"
lazy = true
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "054595ce1ba7787ce91f89a69144b96b7289cb551b4a36d22f213ab3c4f6cc09"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "c171c28f5547890e7b8a55e0dbd7d7b3cec3f964"
lazy = true
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "869ad2fdb13ecaa4d671126d1f2799ee9ca4bb1fa982ab5d2ed8c9aff532a6b8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "80fcf8d125b03da71a3c7bfeac8548ad3587b85a"
lazy = true
march = "avx512"
os = "macos"

    [[finufft.download]]
    sha256 = "bc97684d0c5274dad645c6b2623accac294a7675ac0de0f91115ad952c5825a0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-apple-darwin-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "ba5e49bbce5c747d5a3f982f2eb5babd2b4298ef"
lazy = true
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "18d32ae7b1548ebdc6896f1d5e426b533fe38a6135ce62a6cae2d3326142502c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "82fd3de404288227f312a300591aca046229ca9a"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "b13797b42a4a91eb178d3eba6672daa38f8952870b6dae966604e4fdf12e4555"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "94de9fddd7ee11b4f210dcb51850ba532ed3097d"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "92f340c8b7683c636f9bb3ee6835acb6d450fafc43abdee8d76bddf62b5e084c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "38ed11ad4b2163d02e3ddddc8369e9ab426f1bb7"
lazy = true
libc = "glibc"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "cfea012301a6a7b38b3fb4fb2be723c717af5e44b8afb4097cf257d67e3efee0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-gnu-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "42923b82011c5ef18a6f01ecc4198f94fdbc16bc"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "47f15fa20c9195ce543ec43f883f07e8a62d320f3e64fb71f2536faee42313bf"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a3a620a80d851dba9627c3465be09c5eaa6ef951"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "7b794cd196c998fe1d4fbbc23b6193be3f24a2352b57205c95bf127a8372c8bc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "9395e3ba7b4b2acf56153a688a6ab7977a22d63c"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "9cbcebc5dafc418cf27044b41eff74a524accd2a1f39eedb99ba77d723a818de"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "b80d9adec51ec7472c4d12d34cc2bd69e2d20a37"
lazy = true
libc = "musl"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "abd818e61ccbf5bc7378c576dada11cfda062ebe3c5b0397f55df6d5f1ea1cd0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-musl-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "df98da56039a01004cdec176d7cbc879aecc2778"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "035b3d1da7b19d2f8acd1ab08632be0031add2682c03048fa09df6046e22accd"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "59f1269a1dd8c153f85294f2edfbab2b3e0d3f94"
lazy = true
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "8aad7ecca2f066aeb63f7f50fc879b03534ee1517ddfeab701e196721a8c9715"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "ba6923ee6a282eceb27e949ce731800d07009bc6"
lazy = true
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "d6f7e0ce0e1799cb3ceb959ef5221c34ff87c418286096c9b3a04023e2d21fcd"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a84705e7976ef92b8ccdb9cb2d47d7f1bc24d1c5"
lazy = true
march = "avx512"
os = "freebsd"

    [[finufft.download]]
    sha256 = "21ad595e35e5f17edd5cb78c8d3732d705c64a32032b6a91b065ee2da8c9ce8b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "7413c359f2d50ce554e52bfbb3c9a4a9a76d7929"
lazy = true
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "6d366193acac74f46dd47f1cc0cc42a749c9f022664dcbfd620fa02fd41a24ba"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f199ee81267cc57b1d6760914da2e5364fb38baf"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "ddbda3bdefb15f30d3faf30eac0c7c096d7a522dc18db6d06e5625213a1ee837"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "655a34d8ca5d40e917f5086c8967c547a5413940"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "a528fd16bda5ec2df19808b8517693e60038053b8fda947503a465dd9ab56dad"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a884a605db435042e786fe0b11c4a28cf274179"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "99f48b242a4829a694c04aa7579e3e16cab25bb31dfa8ea5d459183e7a3ebd3a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27184c6f607b1a43e2bd35f9de897ea0b60e1d0b"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "82a88209be3aa01315bf2ed162a50b3571cee028c4673a049cb58e4ef18cacde"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30366199bc69c4901535b75531ff8b02818be763"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "8a93b2daf455907c444e772e6bbc16583a6d31cc923a78d2417e73585e5654c4"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a2d54657c2bae69b0f817370c457f9511978b56"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "840fd87a87e194c103f84f73053b477898f8c1c46b5adadf1d176b93af29b0d9"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcf26637d1c2f3b0f49f747640cbfe18ee577c5a"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "9969f6e4644c52809d473a1aa472f2160cd5ccd100daf6dcc9685b583b3ccc42"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5e3dcd105dce3613da78fe0f87294a3ee545512"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "ed0526cb611ce2489023c2099b817fef87143660479280be6fa762dba2a8dc6f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+1/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
