[[finufft]]
arch = "aarch64"
git-tree-sha1 = "aa35a42d42034612505278437c234fdf9a9028cb"
lazy = true
os = "macos"

    [[finufft.download]]
    sha256 = "144b936f013dc982a733a274cdf069bc6505b628d1fb31683b585775d216d952"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "4d6c59c33b9942a6c0167101c6b2005f07fd2a37"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "5044707e110da118e7e1d86ca60301fef85c172bc272017266ea8c7c361cef58"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "71baffe2021e5f297db36f84a5c40107a3bc7ad0"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "83d75635584a579331a1788a0e367064293ea8bfa5546a0ecf0cd92b55942008"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "f7d5b740b8a44e6c106c95a1489d2b77d2a0fc75"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "692d296bfe8caf7d99ae397016c884535a38719271fce7225ee3ec2a5705fc13"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "64e898fc84bf1d7801358898c5ee4f04775dfca3"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "96c9b5510498e5811d75fea4a651cf5e74ef59ecc78e187eb622806619163034"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f145635481dba0dcf2bffb50b25d618c1b6d0f43"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "200413ddb48e9824ce16790b2d70b488c5fe796decb66de92e4e1204efd77c27"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3c2d72dfffa753d485da295453aab382c915739"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "f8506368164ae3bfbf4059b7d89495bdf20f0ca5e29ffdf5b93da49d2ed6aeb2"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "16c620beb90f37bdd0f02e1e195324ee97f4fa97"
lazy = true
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "07373872aa8a4b6744faec21c84dd6f6bf4205e32b639b3a1c57d3a5ef31601e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2f4fa7970ed4ffd212e6513294a1131b0e83b37d"
lazy = true
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "22ce65569d272c922c873e582d5c9998e0c748d758f3bcba965bf10a80cae478"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "c2e5e3dd42620941248085a4ca742532dc66d4fb"
lazy = true
march = "avx512"
os = "macos"

    [[finufft.download]]
    sha256 = "ff7c4d4c43454c78f076bd991a4a915c7d166ef88937e81de220633ac07cdf1e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-apple-darwin-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "149846acd47ad908891e79df1a8b8c8bc0b2b92b"
lazy = true
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "17831af3731b56a86c862b84cabb6d1af89b6ee9597b8889efdc8c1aac708bca"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "5d6c69178e0ba2c471a2cc5b9f809c8e2ce828db"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "9f4667020370a423671a8b01619d1129c2fcb8f0b8c715aaf06ba5be9251829d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "e843319ed4d0dc2ee3648803d8f15de5271bf314"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "76cc6e3ee75d3acd7544b94f6775575cfc0478a7514458d899e04681b02c3ba4"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "da33020b20af76ebc60ca864966a781cc71067d8"
lazy = true
libc = "glibc"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "24c7c5295db809c3c2bb130507a0893bb41b215ce358c547c46b1178531bc02a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-gnu-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "83bcec58ebfc124220ab09a4cc3a596584d81573"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "18d002f133fc4dfed8baac1b51583af8401f338a9f9bbc3d5f84da62e7eaae36"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a6ddff977bcdd9c7e3dedd2c0fa036439d91271f"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "f06d419a15fe03173552b9a13867d8014ff21c053a46b1d28fbd3cbc7fbb7c5f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "10e9fa0f4c97191051ad920b31fe1431796a1631"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "4e7c91652a9098bc738ad3a5120e6de5a14d0853549611bf7f6f5cc73d508517"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "99b2a556c177058006130cd36c33777e68075a6e"
lazy = true
libc = "musl"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "d0d0c35aac27c6baa9caf6ad42a86abb0f8df53e50df87f35ace2dc42a7863a8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-musl-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "bfd6157a27d8f9cf96ca1a6336fb470d079b8e61"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "c26c21d6776053a2cb3c8cd2b2adf398b40d59e218224a6efa963bb8d9e17baf"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "3f4a45c2a180b1b756dcc27bb2b50e1e99ed7bf5"
lazy = true
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "97d37a2ecb3671893151c21a31a5fb3362eac6fc842ebf15b7b6e06a0d62d5f9"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "170f76f09f634a18b0079b8acba0350927c336f6"
lazy = true
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "2e0e3024fee9092e73a860181ae85e85073c444e4fcf04b10d61bed4677688db"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "4218ce07437781406dc50ab3f44594f1ad25cdae"
lazy = true
march = "avx512"
os = "freebsd"

    [[finufft.download]]
    sha256 = "7adb2b28a2c0ef5adf813c6be80ac8b7ef12da13ec488fe9ef74716404e022c1"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "c3349113b3c0516235ccd63b403a271fe4415a4d"
lazy = true
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "8038ca063937ab2ae328cc09be1398c4caeb71e8d7f80b02c0ce148d3f5af54b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59e5743ce3add5344cac3bccb48614d21a44640f"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "cf1b29ba25e61992ff18af847a3bada70c448df48ba8c577bb4b41ab8e5f97a8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f0897a1f3ec8e3a9b0b68e76615b992b9a6f7f8"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "d2a0fabd1f13351ec7beba2afa30db978778e53c2e4a72af8056c0f87dfc2b84"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "490cf3a01951ec8c2bf32efda4346210799c0a1c"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "6019c044d68a0c7d46c2828c12dabb3d66ff806def660bcd6cc7c83e7ad3ea50"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "809bd538c17618c12a4ec868f7c62d5867b8f9ec"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "90d3ba3f871f35221ce4eb165d3dbd5189db722cc9a81e787197116a8df8f9cc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "330f35ee77cdc6cbd59fb8b865365cdd08c2b5e6"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "56dc1a8fa5081863da9cc756c0c89e02ffae2d9590460566b43bde09e7c9676e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfcfd06eb48b05f9012ecd4475a8d50c3f6fc1b3"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "8f13a7aaf13f5794898959e7b829bc3382fb315abb899de834ecffc53e31dfe8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b89b19ec22e15968add042305ebcf57d93baab21"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "7a70f0dade8d9a93072b690ab6d20992c5705631b71904832df7468d125f99dc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d85490166553009cd0a775afbc0c927f28e4f04"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "7ee9deb217c3d762135866cd8e3b23ce77c6cf937510d64cc8d81d8097dafde9"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.4.0+0/finufft.v2.4.0.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
