[[finufft]]
arch = "aarch64"
git-tree-sha1 = "5de3d17b20283f901717fe30c07603927d71459a"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "7948bf3e29f5fc1eaddaf3a0215c1ff8db5ba07db77e3ae83c741c0680d88e86"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "4ec50f8e35a97485655f6e68db625335ea6da7cd"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "cb16f2f353556df3fc5cf5687b64fa2c638bb9fdee096b14b6485b4a65cffa19"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b588f14684e00d8ad71fd9589a66faf3369dfd1"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "f87c3da560ff1e3b28aee0bbdd9db4e2b2be62155fc90d14f365f717d954f300"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b00bc52b07591a6264d038112c48ef63911a59f9"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "49b61eb644bc751f07d1860d22595409a41470114433276f197e71ebbbe78226"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "f95c82ce3cf0d41f5a0baa132d0cdc88867324be"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "67a6b07ec00c9142b0e521e9361d710fd203881bdde7c72b0d04f47402b8619e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "298342bd07f3bcb52f05e0fc3177acb86cb17b16"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "9a9b9064f78fc1a44d05d92a115f11c55d51c097719dcf1fd157859f851928cd"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "b0f43735f286985cf950b8bdc262c9e4af01e888"
os = "windows"

    [[finufft.download]]
    sha256 = "f0076c5dac45b6267dbbcc0defd11972cf4588c5eb5e4cef544198a295d2804c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.i686-w64-mingw32.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "2c1d557f7ab48d64db7802e1ea629e4c0814267c"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "9d419529ac60ed0e220d98d17e392b4ab59535f799b5684c2820cf8daf4a254d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "ff87c234cdda5159a2ab2cc9000f5d4a60481970"
os = "macos"

    [[finufft.download]]
    sha256 = "3d877132e078fb1d5272ae57456cbe470436b82e8656ea61dcec88702af433ad"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.x86_64-apple-darwin.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2a0e878151fa8f3cbe63c49c38570f71b21e566b"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "79e926070b78b2ecfadfbec1f9ba33f2239bfc4a0197933c47c4a4a22713ccc0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.x86_64-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "cf72989af0a434096ce4d8ed071cf8a2cff59c14"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "32d15b1093d23431f96ce7e3b9519d7ec46f23504021e1d4cf9212114c313edc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.x86_64-linux-musl.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "fa0dd43765efe6fd39bd9c44a0f09e2acad22f5a"
os = "freebsd"

    [[finufft.download]]
    sha256 = "9374e67941fabbac40d26827675dc837893e9c7491b1485423e667dde9345432"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.x86_64-unknown-freebsd.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "8dcc8b4f6e304280280e5a86a98dfd610a9216bf"
os = "windows"

    [[finufft.download]]
    sha256 = "942282cc5f94286dc76158cfc801c52bbcd8089181544758aedf52662560fbcd"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.2+1/finufft.v2.0.2.x86_64-w64-mingw32.tar.gz"
