[[finufft]]
arch = "aarch64"
git-tree-sha1 = "511bf9a00d8dae3b205ec48e8f9e8ebe0f722323"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "c9f682f35c1de5d6334f91ffb616318a6a7f63b01f9866647deedba96df93e9c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "8cb6be29ecee95676865620bd9e39af2fda6df77"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "3a8437a55573013a7176a9682a8a0436de2da3f70d2a131caac547acdfdd1f65"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ffcd481e137aea4b38497df7112ca1960095d76a"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "de2bb693b4e440d192b34652c91613e96fa7d905e8c78fc15384967e0dd33ca3"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c9388a7ec1be7979ef9edac369b5d91d552a66e"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "ea1104f9bd0fc261b8d44025d8f62f6f3ea985f0620d5349f9371c43ca6c6a3e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "d40a0755044ae2922f184e3568314c6f85a0e4be"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "344f929a44cb5b0e04553719fbb302586574168a890fbb5cfb3b8eb8647d437e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "436b6984e1e4ce36568f3d887665faca01ae41fb"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "b72fd2c771afbf67f908cf5c52669578a3576b996866f92e0595aff4ebfee772"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "dfdd9aa44d3246b5b1918ffddbe15f955c821501"
os = "windows"

    [[finufft.download]]
    sha256 = "7c9a934fde0b46b2e5bb81cd6ba34c9cf375b12a0dea4c1a1bcd181b2ac9d739"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.i686-w64-mingw32.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "4793ef84f8f1f39c5a79cae576d85d4f82307d95"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "0308f4c59410f87c6f841f57c318f9bff9f3812e1a3d2476f877620c0481d35c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "88e0dcd6ca6922ca74d06185502089226fcb1064"
os = "macos"

    [[finufft.download]]
    sha256 = "012dbee8ca20346198112a86313d7de7790c50820e3c86e845d9111ea86bfede"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.x86_64-apple-darwin.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "5c5bb7908f44f7a450704fef9b4285d5bfb9a93f"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "6647ea1ad17d006c0c8dda7eca75b26012a494b7e8444fea170b522cedd4535b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.x86_64-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "7b80d51d063388996f2661f602f3a74964b6d587"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "923048b9b9fe6983a7da3579d7152c69718a8107ac54c16efb25e1769544d558"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.x86_64-linux-musl.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "b8e3492a3089de025f8741b6cc5e9f40aa98a3b9"
os = "freebsd"

    [[finufft.download]]
    sha256 = "2fb76631d24f0283f409272191f65392acee5634e3ed8bf1a3842a82c8849e91"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.x86_64-unknown-freebsd.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "cc5ebe5ebc1a353f2d39c5700ff3932d775c7c82"
os = "windows"

    [[finufft.download]]
    sha256 = "34d44ae84dbbe59f1baeef5f9a82410bac873f7f07230b63b7d43483c9feaa07"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.3+0/finufft.v2.0.3.x86_64-w64-mingw32.tar.gz"
