[[finufft]]
arch = "aarch64"
git-tree-sha1 = "d0ffab84054386fcdef85e05d7259434ec8ac44b"
lazy = true
os = "macos"

    [[finufft.download]]
    sha256 = "ff09c1ff236cf35caa10e1b2cb0d29fb0470b7148c3b458e3b9da351f95f9817"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "a6cf0bfef5e23c9b214cca87ea7a73429dfb0cd0"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "cf4bd71e9b02fc8ed1408be9aa733977ebdca535534405f1ad14078315e09e48"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "7b18c49505ddf1d9f2e1768f0f9c0c615cf706d1"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "59cf7d2f1d06a7c3389b450326438995d423bc4ed52cc9cf109262e84aa5fc23"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "f5f31066fa58bd0e8f96f38b6f3712bb1e308404"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "00fe375e626ca3f30b3f5546bce401b087b27c3cecb06a1a897b9eec7e310c60"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "28e60a0c46d23c8ab81870e4c36b0d5bd95e4535"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "6bbdb005b42caec6c5529c508e9afefff56c8695a450222e327c4ba58962e4ad"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e9a6ff94d5f3d92278eec3d0af6a3fb03ff9eb3"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "d34c9f8f9664c6c0b4dc71591b41a53ab815d10c3a5eb92a67df0e106290c6e5"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28c0032bb7b24a729ce89cb622a923aa9d6ea4d7"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "382fe9f4504be9ab5402cd841423eb0ef11f18bd40fe6e6cc9008c63c4c9a067"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "e9002e642a1f5d28dced1e167e1086016fc9b99f"
lazy = true
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "55e9cfe8d5b35f28804f7cbbf04cd5c18d0043bd5ffc37fcd3376a3c3efb6238"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2afd385eb755aa1fe2025a4bb5da8b4cb00e62a7"
lazy = true
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "06df47a40eb00428b6f7c532d9297ca2ff32798f2d011b090dc962c34fa5fd1d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "43b02ba16a63d12612bfba7b5b6f8e005f7e3cf8"
lazy = true
march = "avx512"
os = "macos"

    [[finufft.download]]
    sha256 = "a78ae41ee656baacacbb4fc3a219c1a3d399f94655759e87edba064155a41670"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-apple-darwin-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "8f9b503ed1f8cfa5ce4b1a60d25aa3e5496563bc"
lazy = true
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "d825b2f89932c440ef5eee448c812a26a060d335f45e0d29690b3750b2c9e98a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "27bb7b8cece522f72fdd8484e88524018b612b18"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "6adc728f705e76a068c46cb12924d355b2b90f31d6ee7583e7b36bc7d771a481"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "00878fa0398658a18cd3a2614d017df4ab5a4a70"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "da690edfe61dac393d4d42af0c3ab9fc91fa0bae1d2a82b18382efec9ed945d7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2e705e79e91aedb3011f1f693e2644d3a58870d3"
lazy = true
libc = "glibc"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "0edcf539c6da38812831b6066d368231f088bf61b08ead27b6ed58bf92df68fd"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-gnu-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "d601ceb58b5dbe19d7a5af108b6b2cf1a978c694"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "75374150a3abe0e9fd0d8c9b51f15f3a14c90da4d69f3174edd0c55a0f356049"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "300144a807c65a541e32ef1a9cba0924d231f4e5"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "cd6a16385e4a06073c87b64a765330cdd7d13d6c42684dd2c4c7932e5ff748b8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2b02d3dfd64f934dd7990964329fb01b29a2ed40"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "12e3695ff25193698d7702f9523c3ccc16417b58d12b32392aadc6f2245b52ca"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "c22a34ebe3e8d8e5afc1a7c241fde38d94ec53a1"
lazy = true
libc = "musl"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "91974ea536a07e6b925e7b1c2e622c90606154c1bc320fb30d2019d10abd4aff"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-musl-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "6d4eea3b250198a4d046b28a45d505a15935c0a6"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "e199c8250d3e48a1914b1142137d38de5d3582d1306d42e2d4a7ba3b6ea5dc07"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "eed4b1a4fc3b944500add6c532b10ea7b8e2a366"
lazy = true
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "33c56d474767de7d08c77b0be2f0de8529752ca6cc0c7bc99891d1eb301d80dc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "cb05d213f4f7623ff444ff3bf76b3dd28e9ea86e"
lazy = true
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "45918026f061342fabead8d6a41b22dc59c88c5328ac926d83a1663320f922d4"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "022f23504409855701de9ba702131c4f5855b6a5"
lazy = true
march = "avx512"
os = "freebsd"

    [[finufft.download]]
    sha256 = "2088e9eb9b1e453fa6f3a384830c17bad6ce8327a4d47886a346958b9c42da5a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "55e1662633ea5c5215759844c9f620953da67730"
lazy = true
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "0c3c8b40b13e4d4e2f1e4e137a256bfce43c635393c8ea2996883d452beeb6ba"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca47fdd232f51604548e94fe7cdd58cda91f6d59"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "b1006189e9fb111f0d598f9727f5dd99ac0b0f9c8eda34ac2f4d959016e45b62"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e44ee498fd7ba83ad740b06d7bf5b47a36504e35"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "a25ad762ea4d9151b49917b515ee38213b3938dce09b3b7379786e08fd14324e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5c3e843d48c67b7e097f24f073c5fb514813867"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "2809a1dd8f1a1b52555fb0454533f3d50456579f6e59a0714c7cac9fb6471925"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx03-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3c475dc9ed70c7d57cadadeb76db9500f078139"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "c4c44798c69726a93d03ecb460c846c9736b27639ad9ba3cf56bdf77f4a4030a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5181776c0ac07ec2704ddac77f8420764522a013"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "8dcaf55e42ba166e9d9429b896335012d343cfc334ed912d8f47c32b57f3745e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cb8982818585ee975ffbe8f4ab504dbc702ecbc"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "c2aff7baa858d742bb459031ee561b2697bccaea1bce8f87687a3e03a688c136"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44b34eb2351faffc19ef2599d1300d6d6f66306c"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "ddf971ff2cf2c6feef5452c42fbe0270b47aca8ef36944b9d6cbc785012b3df9"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx11-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "720c9d7dc8bc3ecc6e9826e935366000525be58b"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "1687b833684f9392ee5df49297c42df95df8f0549265ca4088eddfeeffde38c8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.3.1+0/finufft.v2.3.1.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
