[[finufft]]
arch = "aarch64"
git-tree-sha1 = "30a93114b2501987df8e4f63d7314ac75d91f0bd"
lazy = true
os = "macos"

    [[finufft.download]]
    sha256 = "ce45f38d8cc47a6dcff09d3d989d85afdb430ca248832da088568552a8d8eb82"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "130a0bda412cb67f02890a53e30d0b847b06c20e"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "40d6546fb97cfd33c01b2705bb1d039b0299a3c45afa6cc9e31a9bc4e39d4ee3"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "a8d5d380bc5fb0b3cf85b938b5f819ea273f91a4"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "f79496e7a6f553250b03d991d784b554a36360acd9d9fef7f4d1f822a0305325"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50a821f8856b8f5a311b220fefaab6e77e1d6f2a"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "002acb3103573148c020e94da1b00d446128ab6f67ec04433ade3dc746e48171"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.armv6l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6fb9441e9f512450a870363fe101c4e9aecd23b8"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "bb12ffc2c66c8c35994b431bf98bdb8d751410778b86dbd9660054cc25b3878c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.armv6l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "22814cf7da26a23ba15cbff2e8052e4cf32c713d"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "4506c54224d6c2f0f0ffa843fc4f98dbef01084e32761d27405c26b036c55bf7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81977254f7f0648b289dc5178606606fd846fcd8"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "7bb3ee4bbd66dc8f5cda2122a94897f3411e1202a9274409240fd31141ba6239"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "6db42fbef6ce180148601f4ed18ebc4c22113f75"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "5ac7637d9cee90ad09f88428b77dde80db10065a6353fb9d8088f42d629b3b9a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "25f23a646e8a0d13a207f700a4569c5e54e920d7"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "14fead2f58a7c388a8a49321fa688339494cd983d0c54c7adb71d7a13314fc42"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f74ae4ffc421d7013e1fcd518a859befcada6ace"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "40355d8c75e0dece3ca56bb96d5826e7e9c6b6b7b10e6477b76dfb668ed2e28f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7014dd161b351027315c8bd1d393c4ef1fab400"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "11a0d1935309a6476722ba756dcc126f9882d24657ca679ac65cb659ce43b7b1"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "4e1f02e929990bcd9873e9559e3d288eeda0ee15"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "a98d1db607ae250b25af58023c68f93e45226a4400adf6f35cfb734107a5276c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "35972dfb32a98afc84cf3d8ff4ecad6d1e9a69ca"
lazy = true
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "2b03ca6b337d08bff4c2a676c8432dbdc7aa940a1d41bc33ca4355f51fc98664"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "86ea48410e1b62175ee9fa1ecd03cb11fbc30a8d"
lazy = true
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "f490f9ac2731ca8135ec23066f91fb3ca7e05e59a5d771ecca897b3726d1c6cc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2ac9db4deddacd9d032921220b270fc0cb4b6054"
lazy = true
march = "avx512"
os = "macos"

    [[finufft.download]]
    sha256 = "660dc7e63a6ac356c960b520e94e525b7920d9ec3f455a927228a72b7f9b1a05"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-apple-darwin-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a52f499b996de6c36233cf2b74ebf974037b2cbf"
lazy = true
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "826f4e7623afcb6f530d670df64686538e45d6a47e15f8372bbf0c4e65e18547"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "8c55756db64912e1136824d6898103715d6582a3"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "69528268843b931e7609d72375b004653176ee0ffc4f5a0bb505c57e645d9c9a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2ede2d58b4474fb61d78f488ed7e5875d32f65f2"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "d2279d6f153a1243c349778c2cf104c08a00b11fc43dff7efe18728ae1c1f269"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "ed00013be56104cd0b1244b46154621dcbaadc6b"
lazy = true
libc = "glibc"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "2e5aa778e2765cbc50d3202654194d7b5d6a4b4299390eb5bcd80c2bb7a84dc4"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-gnu-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "7217db23601bfebfbb8d10030881d676b406bd8e"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "502cf34135b2f09dc6e2ba18ecc011bc635f979a939cb4f38fced888cdedafce"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "49434b8f282b9e7e954952e8ffd0658935f0fa1e"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "e8d1754b50cfbaa5b5cfd5eaf20765ba0729f5513c6e6388d293c2cf27e13653"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "4a1f3bd1c0ee8bc4fe001cf379b2d997642cca6e"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "eec47ee7d91a34f664d28f10e76d132c599c55611609ae69645a5563a75de6a8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "41edcc4c18842633e1a39587383f60c559872c06"
lazy = true
libc = "musl"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "626773cdaa0e7ec4d2b2e957f0c256c3ad50656ed5b5d0bc3d803db58a69d7d7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-musl-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "7496f8f97e9e0214b45c02a803fbe408605cea22"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "8eda32e36ab807b6f92ba445d06b0b9accfd6e289dd274a66dc742488839cf7c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "586abc24ea3a3ac353a42e04f4820520d12b3f76"
lazy = true
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "d8b59f887f5b6368f3696b449b2ca8278ff0c2a57904da221dc921f3e89ada33"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "205ddf36dd7b799954331328bc8d9496f22e145b"
lazy = true
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "483c90b01733d7d9c82837c7f0a897ed58c0d690299df482bdd236ca888761bb"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "ebdf2844bb3666ef9f3526f981982d0139bfb690"
lazy = true
march = "avx512"
os = "freebsd"

    [[finufft.download]]
    sha256 = "77448d30ce50d3f834a6143f1fb333a4cb3cf5e21f61e0b6235c2bad2fc26f80"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "707dda3cc79d2825fd7ad94dcd0fc90069b61c16"
lazy = true
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "f44938ea3bbc8e25e3f3a4c787c1d0d1abf011546505adc9f8dc3b76d751bbbb"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59caeacfb3591186eec668c6a7924921d03abbd4"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "6e78023b99fb198249a63ed3b684fa6398a41cefdc4bfac5548f7dfa2bb3ad72"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c956ca86b81b2119b547d15224e5add5d3d0d7d4"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "99241ddbc0bcf09b834883c34d916f189b04252b05716ae61d43b205c3ff581c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cf6920c17915914f1f126e380aa4c890413bec5"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "c516cfb3e7b00da14ec4c94a4679de6a492a3e88788577d537c1a9f5343ca385"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx03-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cc14caaa3faffef75d199dd1a5e7457ae09be24"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "856a58904238b64e0581cb4e4424361cf604db23a132e40f939f106a6fb4ec95"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2abc5eec258eb028a9b453a99aa3167fe66ee9a5"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "6eeeed2102861b9f3ac2e9666d907a6825dd829cce2b0d290afed484477b2101"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f81d10ec1d5089925f1c455971d0beb84300c0c3"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "7bf543e03fd3edbcd2d0b5012ef47ab4a106bfc3bc49389beab80d68ce6e3dfc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab2ed87dc2ac98ac09f79df1dbedb1c5e6499267"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "afe51831734bf1787fa5ed806b3d73ec207e04e24b96cb4d291177d36cc93a40"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx11-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aac55ba433d9d1c863fc35eda93a3d95d08fb0d"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "d16fee34f5f0bb4924aa65959902e14ffccd5005c9bad092e03e1957262f03e0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.2.0+1/finufft.v2.2.0.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
