[[finufft]]
arch = "aarch64"
git-tree-sha1 = "e7f37a680417283c0e21a8760e9074eb384a83ac"
os = "macos"

    [[finufft.download]]
    sha256 = "b7f110b710186ab81a8e875199d969123fba6fc0578c2234a575f4aab1ea8eb9"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "c91602dc3d5fac96341c9527d74d6309820fb6f1"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "562d7fe0d01d1bfbeb59976cd161df3b9f30cf744fa5c48da65433f0ecd6bfac"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "2de7d1aaac88cf34f01465dd194b26e86add4f99"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "0e0a95c998b51f40088787c56558df3c779d883151257530c6bfd6f5cd7e03ff"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76aaa880a3cf8ed4280b8c763b62bda19a1b8602"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "c659c337e3fb2339a2dd2ad0fa1436db509b08db5640ef89776ac8413a37dfed"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.armv6l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3309567e0cc8f538600cf7eb90670f9eeca70c9b"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "fa81b89999b9ae7f54fb19ad887edc84e57c1be42b8fbf292b8482ba95f37e86"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.armv6l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc6472f734afc51bea89a66c0755be041e8ce1dc"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "fa20718464c0c7d001e822df5907498a73fb1efa7a06509889d09a7664cd9887"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1211db1d6548a95849ba3685e7d0cb86931f77b0"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "7eb40e70c13912b24ebdbd9d28f22aae90bdb0d48adc9ab728deed3972a08641"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "bec6c9c1710b93b86039d47550c2fc7e78dba07a"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "82128579349f30efc8164a0d01ea51fc6810e5b36656af7a39a963c4cdc38527"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "49c564e6a5ce94c0c7ace5724058fb47777b54c2"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "37d4e9efbafa6c6157f3c72b02340bfbc7f793f9181c51e2e444de15b6cc119c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36c00a1c1e0bcac06273ef60a50ebb8826a7ba71"
os = "windows"

    [[finufft.download]]
    sha256 = "9c5c61cb7b7c172e6de10e64153c5ca953c5ef0c8b5aa668a968d3de424c79ac"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c113febcdbf2bd61e30535f5c59d0d8fb0a28c19"
os = "windows"

    [[finufft.download]]
    sha256 = "75b3c8f6c0f473724c2826976c25b6c8e8d744553eb8a9ae706e53bd42ba32a3"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "abae5944cffc82d2c85c1a9948f2f3430c5f7b76"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "f714abc3aa03a546e52b760b91a851b846616a12978e57fc1df291212c56cb4c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "25d221032578db15af1ac5e209516dcb24c68309"
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "d202a498c752335d97d066cb918d747da7d6e63245a07463cc1fc85554499bbf"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "41da766b1465587b3e976ee9d4241bf8d64cc10a"
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "746735a47cc165459d327d551a71fa4eb4de46ab6d5a6cf8c65ea7e9ea17cc26"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "854126db9c1a3d115ef167bf860f8b61bb63cde3"
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "5e0fb11a0f14dcabd3e5581b94efb60211a2ecf47eaa60489f61230ba50f3720"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "908222c61cddab450836a6330178a53717d09b9e"
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "72a74e71c0291503b89b96fe489fb9fcacb08e3654b91a1dc07da81d4baf62a2"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a37fe56131d242c319f89a98e146e8a2ece77617"
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "9a0a3ebf45bee6522b0785a3001d8335c33283642b8c40fcd12c0d728b53de83"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "7400be859b0a9ba09a40ace07bd4405c0e96e6b9"
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "a36f6cca5df3e4e6b39d9ae409da61832de5053a9db682b34c6e26dd0c5ba351"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "1ec68bdaf65d83105956712e25e90a07a4f530a4"
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "07d7c26ad3e4a8697affb72ad5eb6212bf2b7e7539103873a086597a24542667"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2a6c9aa8c113f0863c60aaa0f5afc9771d19f104"
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "0d3a70779f1d2e320c671683258a1f8183f9af80c99505ed87ef40304dd5608b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "d237c02ed7eb21715fe0c44c065019259ea9d6fb"
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "d9fce3ffbdf534d248f45f6870f14731aeb2bcf942240cd89d8ff2bf00879f1e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "64257950369b4c64bc01f2597032d7d908a46c5a"
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "7ffa986ffeedc5ab6b6c99c7a78f15e8c20bf5ab07f3e9f754b85a9ca43732c1"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "f0e6686668c88f1a9f26971336a9c106c725f916"
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "94d6fab789c556d961e831bf7828cbeab8e81c798370d97d7d011511980dfc8c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "4e5210f69929d98f3731c3c72a253279a700a8c1"
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "474d1b335ad5c027c0a4e672e477dd13b0565d4964fcfabbfdea660acb773938"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "060ef76a988287d92ca1125f3e1b323fe8945060"
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "2a02a89b2d7b0f49942b4e77d9325d630691a6d0ac1728cca9c4b91b4c438b03"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a7bb3ca62386e3e7a9097fb4c87e2106e8620d2"
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "52a84dac528e37bda3c643697fbb9338efe714dcd106b80a0c8e6397d08e129f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3cb774fc3127ca4d0e1d36ba161045f8471fa5f"
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "46ab76ca5dd99ffdbdb5bb43acd6ebe5d2a4814811f8bb1f1c26af9308af6cb7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "800406db19e265b14c279ac6b93dde341c42490e"
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "64b911849c51fd58e5fdce16349ef10e9d1cb09915781608adb76569c9dd6076"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abc032a180744a9e0ea33e44eb18c2b8ef5b8104"
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "f4710581152cdd56d2053d1c22fa6cf9c13b6eeca090da1ce0dadc6292fa3320"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7372f160ba032008cdf8be19f2c4f5bc3fffeb2f"
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "5f762cd7a5ab66f7005f88f965fbef559245bafcc6b7a7af5b1cfefec6b05a99"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.0.4+1/finufft.v2.0.4.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
