[[finufft]]
arch = "aarch64"
git-tree-sha1 = "196fdf76829fdf4d2b4cab47b535b0a0d04c2b0b"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "9b05d37c436a793bbffbc5b2e219f60ba439d84393be2a7d58aef3591267c8ce"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "6c3499b62557dd0c66aeda8cfaf7b0df2db1e47e"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "7f07a67db3ecee2dae21854ece0e8225ea4f9acea23b7ab91a8a916a1ba8f753"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv7l"
git-tree-sha1 = "94ec221a30beac4b5ec4c2d398e3dd111d029007"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "d103c84da332d99ebf84f3eab4fe47aaccebcbfb788bf94a4eed0a333d33a4bf"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
git-tree-sha1 = "cd5817fbeee45e6b8b5938c032f1b1903d9f880b"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "74df3b5788b09ab589b93a1679946a553610eced4141b7ee3f2f0a909f51f19a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "4f99082453b8379dc1a045f553f9b36e2d68b4a3"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "2423bdfb9b6693ae9fd0ab51cd4b4cadd0786334f4deaf9547c3945204ef0a17"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "57d00c17539c2f0fbe901601ede9ab500a773e31"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "0a303501e4a1bdb57bd418a7b331b68cad237b6d7631d2cbe4ae4a69cbf063ab"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "1e623d3f74f5bf72f1f458a2542c864764a433ec"
os = "windows"

    [[finufft.download]]
    sha256 = "fc11e08edf8b9b189667f9645c6b4f5992298b302565b491146e6f07e58e4bdc"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.i686-w64-mingw32.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "5a92d2a427265a097e6ab6e6e78003dfa8fec8f3"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "038b809bc0599b8bb00095935913d8e9e77fb1c76247fc3579e1c7e72ab318bd"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "f49622b20f764315071e71f4c0dd82f81cfcc739"
os = "macos"

    [[finufft.download]]
    sha256 = "68c9927808e64b4ba369ac898ee63bdac1a820ee61819a0ff81e3efe7d90237e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.x86_64-apple-darwin14.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "8cb1cfcba4db62c19e6497a22636046303c66fba"
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "890f0168b8a26c5e39acaac3b5c8389ec5744c5a66bebbc01b13af0556ea05c6"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.x86_64-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "b11135299bd181e17fd0ba32594c19b96692aa75"
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "03a23ea5fd525c278d5fe81822569aa76211c5eca6f11b547f1c7ce543e497a2"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.x86_64-linux-musl.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "7f0d9fd8c0f35888c16c5a5b81d143e13fdfb318"
os = "freebsd"

    [[finufft.download]]
    sha256 = "8a9b94e321f12e6a6663dd2565367ea0585d0f1adcfef04df636d46e3e5f6bcb"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "4142f62e61aedfa370885b9f8d08cc524c66d3da"
os = "windows"

    [[finufft.download]]
    sha256 = "6c69e1f26f0352b15c6a837d28acfffa58610b01a4bccfe3e7a1dfc05d160838"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v1.1.2+1/finufft.v1.1.2.x86_64-w64-mingw32.tar.gz"
