[[finufft]]
arch = "aarch64"
git-tree-sha1 = "7950a6de36bf185cdf9d5ed68d690af671ef5188"
lazy = true
os = "macos"

    [[finufft.download]]
    sha256 = "0ef6b96f45f6deb2357de8f248fa096cd1ba4b0a6b769d829e57c585e30045ab"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "3e41a9fa12496a30a57a17339a75d5d9515d62eb"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "28a89a8551b66c466fad6f30b1a525ade6bf4a1f894b26e880c3b6eb336f73e7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "ad4edd2b75651b77d3905388e751c7b6fb5b1e58"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "775cfcd45f39da90fb0e30fa507e681d8c06706558920f23f3d7ac85b2e1a37a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf97957f9d22f0320cfa080ba72a23a3977ac77f"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "f3215e9f0774d8dd67f6a53bacd5062cbc6088e05a410ab3bd49c73c1c3e0cf5"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.armv6l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5b8c558a2539927853809fb09163993d7b266080"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "1f24d3563df4ca1d054b2bc13b554da560976e987802f76a5258c80d258ddcb0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.armv6l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ce863305cabfd04ea33cdee4dc71f49ac6d1412"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "0146929edd465f407861ffb9499d2abcf5766ecb59234c47dab78a099a1da7b0"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "adf2873e75f42042bbdc5c0c2123c9890bf321b2"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "89b0120d5ed05b6b5239ca6af6c28eaa723ff8893a4b0e331b99094e92ceb4b3"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "fa8dac52d06b96052263a6b9067ebb0619b710e4"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "a3b7758271570fc0449a5cb684658f1629d3048dd08f86e87fd1f1c8120f5428"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "4bb1e68c31f165d87294279dd1ad9ce803f4a07d"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "f78e6800b563e2aa72f0d046f12464313a2ab6645f767ba51913a95f5497342a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e85a7b5b498de18e48d2a373f6e238955eb0fcbe"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "bb3c4ee77b6380ddc4f0f5a192aad580b630d0c44f7b6ed129ee23531346d9e2"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3c9b69710debd4dd90e4da699cb746bc2417630"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "7b2123a004d4a1e25d181b116aa3050e1b729ec1da59af2da07f2d06db9b74fb"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "0e4ddafa469ec7de53de60047d01f4853298dc63"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "75fb988382a91b39ea7601c058b39af9c382875312c3f7535d28fdaa266a8571"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "2f76c6bdef5de23da7c4b5f4b783aec619f57246"
lazy = true
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "5f0460aa196765957d8a33574034e53a2a8eb444825fa0cba693a9f17ef5ef4f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "e8ba3fac8d34ba6a57f14ee7dda9c40371a3e1df"
lazy = true
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "0eb5c94a1c22d2c750203298796f5f925bb85ac99742b79e37cf4088f7cdcd07"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a43a94e2c4356fb5e2a1f0d103e047eb6f88a2bc"
lazy = true
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "5fabce512e05ba4462dc7860e750e376d3cca76ab5ec49e3f723e28b3a6d5d14"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "bdd2f1f124fdad240b1189aeedbbed12168794a7"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "f2decd3c790cbad4e499993046b96b971d0161de5ca112c24130c29537fa8c43"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "fb3e7f4b379e95ed8c5644596234212dc77a2299"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "63c0c6942daa8134d872c00eb4ab54bd84c273b27d011778aa52b27cc3e66ff5"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "4aeac920f3621950cfdeae8f241f452ddacb54c2"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "e177c89bf236d2aa8ebbd748e50f8abd587ee9897a7ca8730990194384a2c549"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "68b709c68254eda443246df3196766b7649a6b9c"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "2bf5293df6429334e53fff33b3c05d04e1fe84c2c3111d9fb91c3a700661b424"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "cad0373e660f2ba2d5369f1d54d50d02eeae20ea"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "d68c82859d2a7f65e059523b890aae716a5a612b4285c805c1fad2a50ff9f483"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "6da166932d9ce8262e8bb39eeb13b24934c20fbc"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "41ae767090fe860b2ef73ad25b790ad678812478f8d465926ebb0db8d5c43971"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "a6ed36476a980edd7e117147f29c892d8d4b26cb"
lazy = true
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "f07631460232cfcce4672b0ca6c35daa8327015285c0d75f76713021c91ed4e2"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "f3d8f981d674ad197c40495d8ddab5bd51e82858"
lazy = true
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "bc1157ac3069b7bc904f831869f76ce94c0a54f130635d0f8d06e7c19f797806"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "fdfcc14b0f78dda84a1c1da779afa959c190ffd6"
lazy = true
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "0b8c2c8f935671850147f6f769d3d2a798627f8615d04df98b05ff5e7f35e469"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62a4d9964d6d7b36747c691719ed463f92f6210a"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "b36fbb27655b77c9b9aa03978b2af8ff565535ba4f35e0742aca6e6979e5810d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "602a4ffa15228fa8709215705d38ba76ce925113"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "f9b22147639bd63edf1ea95b8901455390a23c71c4844a9f2b14dceb524da3e7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4533f64fd1668f0003808fb2491adaf153b19131"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "77bb5715d20672e51e3a95756baabb3258e725f6893bca32d79371d9e6593c7b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b05034109e1b2db81cf84811b3b3305597468d50"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "2d48e4bff77b5209437d557a5367ce6bad75cd6b52f07e2e1438ef2907382145"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a5f4e7ed3abc38b55cca5c7e997306531aebb9f"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "21b1262690fda63f6e03d618a1b6af3561cd83d74f73799310586f0a0a08586c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a5ad5136a898b7bbac01276f5d69502717c37a9"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "0ea5f9ef2bd0b53da98765999798f20c25e34b66273291f09e2193e9be53ac43"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+0/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
