[[finufft]]
arch = "aarch64"
git-tree-sha1 = "27336a72e8c13951e409ea634bf4d328170d780d"
lazy = true
os = "macos"

    [[finufft.download]]
    sha256 = "ec825ab20f64fe3c4cf2eb5baf83692b8e286eaca4daf1c14bd5f400444a148f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.aarch64-apple-darwin.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "e30e5118da553a649d1592d7ed45bb987ca1a7bc"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "16c6cebc4a1987326f72c7602d8762c5d5fcefa8d02c912d4970bb4daec6a774"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.aarch64-linux-gnu.tar.gz"
[[finufft]]
arch = "aarch64"
git-tree-sha1 = "dfeb08a81499d50507c2f48a3e156e349c859382"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "f395ba4283aea1715318ecdbe0bebb0b1806b34684da36aa22e22fbf47d681d8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.aarch64-linux-musl.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db09f22364305ed9e826f198466c2e87e961026e"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "c9b5d2d3b928d4776dc99e7f5b341305271528a5f83ac8878233e647419f35ee"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.armv6l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71b4b785ea0601cd29a5358b46eb52f6bedddeaa"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "cabe7d425745f6d76bba85443b9ff100eae6b4b58d07e185b3d7c997c1cc02e5"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.armv6l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef49161da577fd6f2c6959b674f4fc46e52380a5"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "dd4e1580d8845f8f44974c420a4a77f7ffe4716626f156945719c6df6645266f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[finufft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e761a0ebe6d40a50551d8d9603afb327dbfe85a5"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "b777cc8a33d3c08b34c75372b5e5a66603b76c84ecdc44555433f76cd5ac8798"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "fb1fc23ec649d3542d27efe34db6e8567e1bdc53"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "aa64b82fdea38f7d0ca4d05d6f7f12972d832e970f89f4b7fdb9cfc2a9c1d87d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.i686-linux-gnu.tar.gz"
[[finufft]]
arch = "i686"
git-tree-sha1 = "39667007956750a9dbb9f0f8beaafd9afeb196de"
lazy = true
libc = "musl"
os = "linux"

    [[finufft.download]]
    sha256 = "4ec49bcdb94bd5ef8397ede5893db52d8ded828bc6fb234f5a84201888e7463d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.i686-linux-musl.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f28163b7abd22e18549a8df685f9d9c1ae680818"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "7c587bd6b66e27ae178081360b3b37bcbb65c78508c8e2a570ed0f04ab62f44f"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[finufft]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "192a5af3d53475e79e4ac267bcca02e2fd438ee5"
lazy = true
os = "windows"

    [[finufft.download]]
    sha256 = "76616dc7451b8ed484a7abddcfe6d51ef5692202a44c6398dd62638b9c1246f6"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[finufft]]
arch = "powerpc64le"
git-tree-sha1 = "77fe12bcf67a121d92518ef0198f7f11d2b1d4cb"
lazy = true
libc = "glibc"
os = "linux"

    [[finufft.download]]
    sha256 = "161aac712196667dc0df1e4c863e27f585b8c95fc391b6f441575f3a2bc8e0d8"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "8add1eb751aa2a9e0387bbb5c2d3ab8bc7edcfe0"
lazy = true
march = "avx"
os = "macos"

    [[finufft.download]]
    sha256 = "475e8074951c7327eaa08fc8b08e8b16aab61367bc893172234cb0c1974b1bf9"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-apple-darwin-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "dc901c6c5eedba6efb02bdf20ce7c5a0fad61a13"
lazy = true
march = "avx2"
os = "macos"

    [[finufft.download]]
    sha256 = "b76440f9be75a23ebdb0c23bad5f9f1ba04b744dac4f709e1ce4b34836dafc2e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-apple-darwin-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "3f6f150872541978cc7c06342455e91d89d9541f"
lazy = true
march = "avx512"
os = "macos"

    [[finufft.download]]
    sha256 = "b806b7faab51114e3104da82fc9dda0d63bcf2835b37ee174701d00cc92f9f3e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-apple-darwin-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "efa4643e4bf871a0db34c71e48bac536786d5c9b"
lazy = true
march = "x86_64"
os = "macos"

    [[finufft.download]]
    sha256 = "9d74c373cbcf8aa93c15ef54b8b36ee3762546486cd8a94c9af6800797cbba9e"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-apple-darwin-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "b1b0beb826085a2e7c660d3b909f1cb53bdde540"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "adbbdafbd9e5cd949d501617ea421c332c7731bff97ca7058f34e37b2e854593"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-gnu-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "e463f4b732501230efad7e615463b915a9fc9a1a"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "19279a43f5249a1b0e0a7979096491c8764945cfbb86563b8fef085bc640a90b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-gnu-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "130224660e60cd1fd661e51edeaefdc6320f457d"
lazy = true
libc = "glibc"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "510e5bc9c6d26b0cca42f8fab19aa2cccb0a2aa947a80ddd32624307ab4a073c"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-gnu-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "97c3e1d560695991a876c857eacf0e9add6ad2fd"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "187424c5fe91fada36aa34508f31ed207b01c33fe9ecebce03c2a2741d958e58"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-gnu-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "b0dcc35e6b7784a26762a7f1c71dbb48344c69f5"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[finufft.download]]
    sha256 = "ed41ce982f7e063a82ef91a95cd13616fbb7200edb193cc4cf55e0c42bb6e555"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-musl-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "4aa880ad10b8e19ee534a6a6914d262a4f89c83c"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[finufft.download]]
    sha256 = "7704aa60cf4cdd00c1b397fe4cc16c9644a350a1f2620e98129891e32d1ee595"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-musl-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "c81eed5965c7f5058a2d1bbb31b858725ea0b07d"
lazy = true
libc = "musl"
march = "avx512"
os = "linux"

    [[finufft.download]]
    sha256 = "9c2e5099de9bd3e5970e3ff469c9656720b8d66591d640d3e7f31e34a97703e7"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-musl-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "3d715683e05eea4aedb040f1d57f79176a496b68"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[finufft.download]]
    sha256 = "478a95655e4b22892955a823146bf81ebaccf1913dd536f70117c3f267582315"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-linux-musl-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "ccaf460d0fe948a2a1acc90d9a8d8510a803609d"
lazy = true
march = "avx"
os = "freebsd"

    [[finufft.download]]
    sha256 = "650a35da6a9c4deb6fc3545f4611a92e8192756244f0e74f05d3b6ce6e80c64b"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-unknown-freebsd-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "54d524e3a6a4bb842499ed400affbe8ebf5c2335"
lazy = true
march = "avx2"
os = "freebsd"

    [[finufft.download]]
    sha256 = "5038758336ace0bb7e5f9a84541b50a3d716e4e1c99d644b02c02e21d518246a"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "64696ff9ab3aac0ad5c52b37e5db4449660c7202"
lazy = true
march = "avx512"
os = "freebsd"

    [[finufft.download]]
    sha256 = "3454e85e3b791ebafbba6b549b8fe2300f0ddf23d46b41271fb01768ecbe4a15"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
git-tree-sha1 = "3dc6ca37bd2f7292f404a50a5ab1b951e5b6d4cf"
lazy = true
march = "x86_64"
os = "freebsd"

    [[finufft.download]]
    sha256 = "528cb794007a49ba77c5da3b33e2db41afcdca87111ada6dad97efac736dcc37"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f03b7b249367d5226809b668d7cbf91b9bee31fd"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "d4dcc8c61ced94e5b4c22292af71e92d0d9a5eaff10565457de4d4c623b65bc1"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3401881b59ed33124eae77a156f2f2c96a71f517"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "3548dbefb5b61dac47945673b0065f92b10879513f92eacbbf5c8c17b39dec05"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b871242dd305f7a5ca97e832b243e208c57f17df"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "ac3490328279f34d88fc071859fe1dacc0520a9137744e34bba3cf5414f315f4"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca24f0b82ba22566c77f1e41c88c4afb32eae9e5"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "c9f4523c3013a13ef10db11a8a3725b4c56b5eb1b0e220705fd61d49aeb38696"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70c0a905294def840310bcf47421bec5ff138bc0"
lazy = true
march = "avx"
os = "windows"

    [[finufft.download]]
    sha256 = "11933290ef7d74f432ba2035877714fbc547236c1ddafb4b90d628e099ff23e2"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14846470a3a5870027b7e2198485c686ee4f3811"
lazy = true
march = "avx2"
os = "windows"

    [[finufft.download]]
    sha256 = "02b18ee91c0d99871ebe62096489ab8c45565f10268b3340ffa30ba730a6b517"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4751678403e989bdff58ea55c9893e9c28a3f56"
lazy = true
march = "avx512"
os = "windows"

    [[finufft.download]]
    sha256 = "693135fcc5f571afcf4f5404a0ab367033cc698b02a5e41cfcb01256ddd2086d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+avx512.tar.gz"
[[finufft]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bbc70c3c1bb0e3d3022bdfacf69e53916e93594"
lazy = true
march = "x86_64"
os = "windows"

    [[finufft.download]]
    sha256 = "ac05f7b8b1142c68bd325151e939cf0ba7a68892120b96333a8835fc7cea4e0d"
    url = "https://github.com/JuliaBinaryWrappers/finufft_jll.jl/releases/download/finufft-v2.1.0+1/finufft.v2.1.0.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
